// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWpww08NgndNB5CxQ2Ekao0wWABGolQAk',
    appId: '1:169972296739:web:d671605f2b8ed82b7e9596',
    messagingSenderId: '169972296739',
    projectId: 'playground-2025-02',
    authDomain: 'playground-2025-02.firebaseapp.com',
    databaseURL: 'https://playground-2025-02-default-rtdb.firebaseio.com',
    storageBucket: 'playground-2025-02.firebasestorage.app',
    measurementId: 'G-NZ2PYGC1Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl7_jaoBGwDbSIk2e9vu2GbzVpxCvcHuI',
    appId: '1:169972296739:android:66e784ceb1f4bfeb7e9596',
    messagingSenderId: '169972296739',
    projectId: 'playground-2025-02',
    databaseURL: 'https://playground-2025-02-default-rtdb.firebaseio.com',
    storageBucket: 'playground-2025-02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEHoEqVHHhlXDV2-wRxx7ZqxxqRKUudhY',
    appId: '1:169972296739:ios:8f47375baf514d2c7e9596',
    messagingSenderId: '169972296739',
    projectId: 'playground-2025-02',
    databaseURL: 'https://playground-2025-02-default-rtdb.firebaseio.com',
    storageBucket: 'playground-2025-02.firebasestorage.app',
    iosClientId: '169972296739-tojc7ahltsihhqad9mr7gon55h9rq9nn.apps.googleusercontent.com',
    iosBundleId: 'com.example.playground2502',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEHoEqVHHhlXDV2-wRxx7ZqxxqRKUudhY',
    appId: '1:169972296739:ios:8f47375baf514d2c7e9596',
    messagingSenderId: '169972296739',
    projectId: 'playground-2025-02',
    databaseURL: 'https://playground-2025-02-default-rtdb.firebaseio.com',
    storageBucket: 'playground-2025-02.firebasestorage.app',
    iosClientId: '169972296739-tojc7ahltsihhqad9mr7gon55h9rq9nn.apps.googleusercontent.com',
    iosBundleId: 'com.example.playground2502',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWpww08NgndNB5CxQ2Ekao0wWABGolQAk',
    appId: '1:169972296739:web:c615fcf9f0e99b0e7e9596',
    messagingSenderId: '169972296739',
    projectId: 'playground-2025-02',
    authDomain: 'playground-2025-02.firebaseapp.com',
    databaseURL: 'https://playground-2025-02-default-rtdb.firebaseio.com',
    storageBucket: 'playground-2025-02.firebasestorage.app',
    measurementId: 'G-X28MY50LSG',
  );
}
